name: Update generated files

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Every 24 hours

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run main.py
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: python main.py
      - name: Commit and push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add generated/
          git commit -m 'Update generated files' || echo "No changes to commit"
          git push
